import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Contact from "@/components/Contacts"
import Card from "@/components/Card";
import About from "@/components/About";
import Banner from "@/components/Banner";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pokedex Livros</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.webp" />
      </Head>
      <Header />
      <main>
        <Banner />
        <section>
          <About />
        </section>
        <section className={styles.cardSlots}>
          <Card />
          <Card />
          <Card />
        </section>
      </main>
      <Contact />
      <Footer />
    </>
  );
}
